---
abstract: 'The one stop shop for parsing static column width text tables!'
author:
  - 'Evan <me@evancarroll.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DataExtract-FixedWidth
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  perl: 5.10.0
version: 0.03
